print("===========")
print("AKIBA STUDENT CARD:")
StudentName=input("Enter your name:")
StudendId=input("Enter your id:")
Department=input("Enter your department")
Year=input("Enter year:")
university=input("Enter university:")
phone=input("Enter your phone number:")
print("============")