print("===============================")
print("STUDENT INTRODUCTION")
print("========================")
full_name = input("Enter your full name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter one programming goal: ")
